version: "3.0"
services:
  tomcat-mysql-sml:
    image: smp-sml-tomcat-mysql:${SMP_VERSION}
    container_name: smp-sml-tomcat-mysql
    volumes:
      - ./properties/db-scripts:/tmp/custom-data/  # init script.
    ports:
      - "3908:3306"
      - "8982:8080"
      - "6902:6901"
      - "8953:53"
