---
excludes:
  paths:
  - pattern: ".mvn/**"
    reason: "BUILD_TOOL_OF"
    comment: "This directory contains Maven build tool."

  - pattern: "smp-docker/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."

  - pattern: "smp-soapui-tests/**"
    reason: "TEST_OF"
    comment: "This directory contains tests."

  - pattern: "smp-ui-tests/**"
    reason: "TEST_OF"
    comment: "This directory contains tests."

  - pattern: "smp-wls-deploy/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."

  scopes:
  - pattern: "checkstyle"
    reason: "BUILD_DEPENDENCY_OF"
    comment: "Packages for code styling checks (testing) only."

  - pattern: "devDependencies"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "jacocoAgent"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for code coverage (testing) only."

  - pattern: "jacocoAnt"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for code coverage (testing) only."

  - pattern: "test.*"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."

  - pattern: "annotationProcessor"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "compileClasspath"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "compileOnly"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."
