version: "3.0"
services:
  tomcat-mysql:
    image: smp-tomcat-mysql:${SMP_VERSION}
    container_name: smp-tomcat-mysql
    volumes:
      - ./properties/db-scripts:/tmp/custom-database-scripts/  # init script.
    ports:
      - 3907:3306
      - 8981:8080
      - 6901:6901


